# Generated by Django 4.0.5 on 2022-07-15 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=60)),
                ('comp_name', models.CharField(blank=True, max_length=60, unique=True)),
                ('password', models.CharField(blank=True, max_length=60)),
                ('user', models.OneToOneField(blank=True, max_length=60, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodname', models.CharField(blank=True, max_length=100)),
                ('desc', models.CharField(blank=True, max_length=70, null=True)),
                ('price', models.FloatField()),
                ('prodimg', models.ImageField(blank=True, default='', null=True, upload_to='product')),
                ('shop', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seller.seller')),
            ],
        ),
    ]
